config_name: base_modlns,k=10
description: "base config, k=10. Without weight sharing as mentioned in the paper ie., using the new weights for each iteration>"

n_layers: 5
k_iters: 10
epochs: 50
pretrained: False

dataset_name: modl_dataset
dataset_params:
  dataset_path: 'data/dataset.hdf5'
  sigma: 0.01
val_data: False
batch_size: 1

model_name: base_modl
restore_weights: False #False, best, inter, final
restore_path: 'workspace/base_modl,k=1/checkpoints/'

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True
